#!/bin/bash

# defaults
clean=0
nvim=0

authorname=""
authoremail=""

# usage
function usage() {
	echo "use: $0 [options]"
	echo "  -c  do clean installation"
    echo "  -n  install for nvim"
	echo "  -h  show this usage"
	exit 0
}

# process options
while getopts ":a:e:gcnh" arg; do
	case "$arg" in
		c) clean=1 ;;
        n) nvim=1 ;;
		h) usage ;;
	esac
done

if [[ $nvim -eq 1 ]]; then
    configpath="$HOME/.config/nvim"
    vimrcfile="$HOME/.config/nvim/init.vim"
else
    configpath="$HOME/.vim"
    vimrcfile="$HOME/.vimrc"
fi

# clean current vim stuff
if [[ $clean -ne 0 ]]; then
    [[ "$configpath" != "" ]] && rm -rf "$configpath"
    [[ "$vimrcfile" != "" ]] && rm -f "$vimrcfile"
fi

# put the vimfiles in place
[[ ! -d "$configpath" ]] && mkdir "$configpath"
cp -a ./vimfiles/* "$configpath/"
# copy new vimrc
cp -a ./vimrc "$vimrcfile"

if [[ $nvim -eq 1 ]]; then
    nvim +PlugInstall +qall
else
    vim +PlugInstall +qall
fi
